networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb_vol:
    driver: local
    name : mariadb_vol
    driver_opts:
      type: none
      o: bind
      device: /home/nerrakeb/data/mariadb
  wordpress_vol:
    driver: local
    name: wordpress_vol
    driver_opts:
      type: none
      o: bind
      device: /home/nerrakeb/data/wordpress

services:
  nginx:
    build: requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_vol:/var/www/html
    env_file:
      - ./.env
    depends_on:
      - adminer
      - redis
    restart: always

  wordpress:
    build: requirements/wordpress
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    expose:
      - 9000
    volumes:
      - wordpress_vol:/var/www/html
    env_file:
      - ./.env
    depends_on:
      - mariadb
    restart: always

  mariadb:
    build: requirements/mariadb
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb_vol:/var/lib/mysql
    env_file:
      - ./.env
    restart: always

  redis:
    build: requirements/bonus/redis
    image: redis
    container_name: redis
    ports:
        - "6379:6379"
    depends_on:
      - wordpress
    networks:
        - inception
    volumes:
      - "wordpress_vol:/var/www/html"
    restart: always

  ftp_server:
    build: requirements/bonus/ftp_server
    image: ftp_server
    container_name: ftp_server
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - "wordpress_vol:/var/www/html"
    networks:
      - inception
    env_file:
      - ./.env
    restart: always

  adminer:
    build: requirements/bonus/adminer
    image: adminer
    container_name: adminer
    depends_on:
      - mariadb
    expose:
      - 9001
    networks:
      - inception
    restart: always

  static_page:
    build: requirements/bonus/static_page
    image: static_page
    container_name: static_page
    ports:
      - '4004:4004'
    networks:
      - inception
    restart: always
    
